#!/bin/bash

TARGET=uno

gyp uno.gyp --depth=. -f make --generator-output=./build/makefiles

echo "Compiling..."
make -C ./build/makefiles/ $TARGET
if [ $? -ne 0 ]; then
  exit 1
fi

./build/makefiles/out/Default/"$TARGET"
